--Replication and Failover
--Lab 10.1

SELECT SYSTEM$DISABLE_DATABASE_REPLICATION('weather');


USE ROLE ACCOUNTADMIN;
CREATE ROLE myrole;
GRANT CREATE FAILOVER GROUP ON ACCOUNT
  TO ROLE myrole;


USE ROLE myrole;

CREATE OR REPLACE FAILOVER GROUP myfg
  OBJECT_TYPES = USERS, ROLES, WAREHOUSES, RESOURCE MONITORS, DATABASES
  ALLOWED_DATABASES = weather
  ALLOWED_ACCOUNTS = eyytunm.demo1
  REPLICATION_SCHEDULE = '10 MINUTE';

--Switch to target account

USE ROLE ACCOUNTADMIN;
CREATE ROLE myrole;
GRANT CREATE FAILOVER GROUP ON ACCOUNT
  TO ROLE myrole;


USE ROLE myrole;

CREATE FAILOVER GROUP myfg
  AS REPLICA OF eyytunm.demo1;


GRANT REPLICATE ON FAILOVER GROUP myfg TO ROLE my_replication_role;
USE ROLE my_replication_role;
ALTER FAILOVER GROUP myfg REFRESH;


GRANT FAILOVER ON FAILOVER GROUP myfg TO ROLE my_failover_role;


--Lab 10.2

USE ROLE ORGADMIN;

-- View the list of the accounts in your organization
-- Note the organization name and account name for each account for which you are enabling replication
SHOW ACCOUNTS;

-- Enable replication by executing this statement for each source and target account in your organization
SELECT SYSTEM$GLOBAL_ACCOUNT_SET_PARAMETER('<organization_name>.<account_name>', 'ENABLE_ACCOUNT_DATABASE_REPLICATION', 'true');


USE ROLE ACCOUNTADMIN;

CREATE ROLE myrole;

GRANT CREATE FAILOVER GROUP ON ACCOUNT
    TO ROLE myrole;


SHOW REPLICATION ACCOUNTS;


SHOW FAILOVER GROUPS;
SHOW DATABASES IN FAILOVER GROUP myfg;
SHOW SHARES IN FAILOVER GROUP myfg;


USE ROLE myrole;

CREATE FAILOVER GROUP myfg
    OBJECT_TYPES = USERS, ROLES, WAREHOUSES, RESOURCE MONITORS, DATABASES, INTEGRATIONS, NETWORK POLICIES
    ALLOWED_DATABASES = db1, db2
    ALLOWED_INTEGRATION_TYPES = API INTEGRATIONS
    ALLOWED_ACCOUNTS = myorg.myaccount2
    REPLICATION_SCHEDULE = '10 MINUTE';


USE ROLE ACCOUNTADMIN;

CREATE ROLE myrole;

GRANT CREATE FAILOVER GROUP ON ACCOUNT
    TO ROLE myrole;


USE ROLE myrole;

CREATE FAILOVER GROUP myfg
  AS REPLICA OF myorg.myaccount1.myfg;



GRANT REPLICATE ON FAILOVER GROUP myfg TO ROLE my_replication_role;
GRANT REPLICATE ON FAILOVER GROUP myfg TO ROLE my_replication_role;



USE ROLE my_replication_role;

ALTER FAILOVER GROUP myfg REFRESH;



GRANT FAILOVER ON FAILOVER GROUP myfg TO ROLE my_failover_role;

  
